# Generated by Django 5.1.1 on 2024-09-22 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='study_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('study_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
