# Generated by Django 5.1.1 on 2024-09-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_studentanswer_aigrading_studentquizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
