# Generated by Django 5.0.9 on 2024-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursefeedback",
            old_name="rating",
            new_name="clarity_of_explanation",
        ),
        migrations.RenameField(
            model_name="instructorfeedback",
            old_name="rating",
            new_name="approachability",
        ),
        migrations.RenameField(
            model_name="trainingprogramfeedback",
            old_name="rating",
            new_name="learning_outcomes",
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="course_material",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="course_structure",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="practical_applications",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="support_materials",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instructorfeedback",
            name="communication_skills",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instructorfeedback",
            name="engagement",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instructorfeedback",
            name="professionalism",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instructorfeedback",
            name="subject_knowledge",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingprogramfeedback",
            name="organization",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingprogramfeedback",
            name="relevance",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingprogramfeedback",
            name="resources",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingprogramfeedback",
            name="support",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=0
            ),
            preserve_default=False,
        ),
    ]
