# Generated by Django 5.1.1 on 2024-09-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizanswer_remove_answer_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField(max_length=255)),
                ('answertext_1', models.TextField(max_length=255)),
                ('answertext_2', models.TextField(max_length=255)),
                ('answertext_3', models.TextField(max_length=255)),
                ('answertext_4', models.TextField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('answertext_1', 'Answer 1'), ('answertext_2', 'Answer 2'), ('answertext_3', 'Answer 3'), ('answertext_4', 'Answer 4')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quizgrading',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quizgrading',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='subject',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_answer',
            field=models.CharField(default='No answer', max_length=255),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestionanswer'),
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizGrading',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
