# Generated by Django 5.1.1 on 2024-09-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userpersonalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalize', to='user.user'),
        ),
    ]
